services:
  app:
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/home/node/app
      - ./uploads:/home/node/app/uploads
    command: sh -c "yarn install && npx prisma migrate dev --name init && npx prisma migrate deploy && yarn dev"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"
